CMD ["sh", "-c", "echo 'APP_ENV=production' > /var/www/html/.env && \
    echo 'APP_DEBUG=false' >> /var/www/html/.env && \
    echo 'APP_URL=https://jobportal-y56o.onrender.com' >> /var/www/html/.env && \
    echo 'DB_CONNECTION=mysql' >> /var/www/html/.env && \
    echo \"DB_HOST=$DB_HOST\" >> /var/www/html/.env && \
    echo \"DB_PORT=$DB_PORT\" >> /var/www/html/.env && \
    echo \"DB_DATABASE=$DB_DATABASE\" >> /var/www/html/.env && \
    echo \"DB_USERNAME=$DB_USERNAME\" >> /var/www/html/.env && \
    echo \"DB_PASSWORD=$DB_PASSWORD\" >> /var/www/html/.env && \
    echo 'DB_SSL_CA=/var/www/html/ca.pem' >> /var/www/html/.env && \
    echo 'CACHE_STORE=file' >> /var/www/html/.env && \
    echo 'SESSION_DRIVER=file' >> /var/www/html/.env && \
    php artisan config:clear && \
    php artisan cache:clear && \
    php artisan serve --host=0.0.0.0 --port=8080"]